library( "miscTools" )

set.seed( 123 )
m1 <- matrix( rnorm( 9 ), ncol = 3 )
print( m1 )
try( semidefiniteness( m1 ) )
try( semidefiniteness( m1, method = "eigen" ) )
try( semidefiniteness( m1, positive = FALSE ) )
try( semidefiniteness( m1, positive = FALSE, method = "eigen" ) )

m2 <- crossprod( m1 )
print( m2 )
semidefiniteness( m2 )
semidefiniteness( m2, method = "eigen" )
semidefiniteness( m2, positive = FALSE )
semidefiniteness( m2, positive = FALSE, method = "eigen" )
semidefiniteness( -m2 )
semidefiniteness( -m2, method = "eigen" )
semidefiniteness( -m2, positive = FALSE )
semidefiniteness( -m2, positive = FALSE, method = "eigen" )

m3 <- cbind( m2, - rowSums( m2 ) )
m3 <- rbind( m3, - colSums( m3 ) )
print( m3 )
semidefiniteness( m3 )
semidefiniteness( m3, method = "eigen" )
semidefiniteness( m3, positive = FALSE )
semidefiniteness( m3, positive = FALSE, method = "eigen" )

m4 <- m3 * 1e6
print( m4 )
# rcond(m4)
# det(m4)
semidefiniteness( m4 )
semidefiniteness( m4, method = "eigen" )
semidefiniteness( m4, positive = FALSE )
semidefiniteness( m4, positive = FALSE, method = "eigen" )

m5 <- diag( -1, 4, 4 )
semidefiniteness( m5 )
semidefiniteness( m5, method = "eigen" )
semidefiniteness( m5, positive = FALSE )
semidefiniteness( m5, positive = FALSE, method = "eigen" )

m6 <- matrix( -1, 4, 4 )
semidefiniteness( m6 )
semidefiniteness( m6, method = "eigen" )
semidefiniteness( m6, positive = FALSE )
semidefiniteness( m6, positive = FALSE, method = "eigen" )

m7 <- diag( c( -1, -3 ) )
print( m7 )
semidefiniteness( m7 )
semidefiniteness( m7, method = "eigen" )
semidefiniteness( m7, positive = FALSE )
semidefiniteness( m7, positive = FALSE, method = "eigen" )

m8 <- symMatrix( c( 2, -1, 0, 2, -1, 2 ) )
print( m8 )
semidefiniteness( m8 )
semidefiniteness( m8, method = "eigen" )
semidefiniteness( m8, positive = FALSE )
semidefiniteness( m8, positive = FALSE, method = "eigen" )

m9 <- symMatrix( rnorm( 6 ) )
print( m9 )
semidefiniteness( m9 )
semidefiniteness( m9, method = "eigen" )
semidefiniteness( m9, positive = FALSE )
semidefiniteness( m9, positive = FALSE, method = "eigen" )
